# Generated by Django 3.0.5 on 2020-06-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200608_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
