# Generated by Django 3.0.5 on 2020-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200608_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profilepic',
            field=models.ImageField(default='download.jpeg', upload_to='profilepic'),
        ),
    ]
