# Generated by Django 3.0.5 on 2020-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200507_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=1, max_length=250, verbose_name='title'),
            preserve_default=False,
        ),
    ]
