# Generated by Django 3.0.5 on 2020-05-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
